apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-plx7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-plx7
    app.kubernetes.io/part-of: tkrw-pr712-0075-0019-app
  name: devfile-sample-plx7
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-plx7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-plx7
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0019-tenant/tkrw-pr712-0075-0019-app/devfile-sample-plx7@sha256:4a2a099d5a426c68b8952b79b9e29ea4e528112ff965f6452ebd6e5c8f5b64c8
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
